### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by firefox200** [Gyvastis/lesmillsondemand-video-scraper#2]
Hello,

I am currently getting the following error when trying to downlaod some videos:

yarn run v1.22.4
$ node src/download.js
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Volumes\iSafe\LesMills\bodypump_110_55_min.mp4'
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at WriteStream.onerror (_stream_readable.js:746:7)
    at WriteStream.emit (events.js:311:20)
    at internal/fs/streams.js:320:12
    at FSReqCallback.oncomplete (fs.js:154:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Volumes\\iSafe\\LesMills\\bodypump_110_55_min.mp4'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Do you know what is causing the issue?

Thank you very much for your help!

**Comment by Margalida-MB** [comment]
Hi! I'm getting the exact same error 😢 
I've tried changing the scrape category, but the error persists.
May it have something to do that I don't actually have an account on Les Mills website?
Thanks a lot! 😄

**Comment by sabahmax-dev** [comment]
Thanks for reporting this! The `ENOENT` error is happening because the download destination directory doesn't exist yet. I've opened PR #12, which ensures the output folder is created before writing the video file, so this should resolve the issue. 🎉
